/*
 * Handelsregister bevragen
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op het Handelsregister beschikbaar gesteld.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Adres;

/**
 * CorrespondentieAdresEigenaar
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-27T13:10:40.228Z[Etc/UTC]")
public class CorrespondentieAdresEigenaar {
  public static final String SERIALIZED_NAME_RSIN = "rsin";
  @SerializedName(SERIALIZED_NAME_RSIN)
  private String rsin;

  public static final String SERIALIZED_NAME_IDENTIFICATIE_HANDELSREGISTER_NATUURLIJK_PERSOON = "identificatieHandelsregisterNatuurlijkPersoon";
  @SerializedName(SERIALIZED_NAME_IDENTIFICATIE_HANDELSREGISTER_NATUURLIJK_PERSOON)
  private String identificatieHandelsregisterNatuurlijkPersoon;

  public static final String SERIALIZED_NAME_AANSCHRIJFWIJZE = "aanschrijfwijze";
  @SerializedName(SERIALIZED_NAME_AANSCHRIJFWIJZE)
  private String aanschrijfwijze;

  public static final String SERIALIZED_NAME_ADRES = "adres";
  @SerializedName(SERIALIZED_NAME_ADRES)
  private Adres adres;


  public CorrespondentieAdresEigenaar rsin(String rsin) {
    
    this.rsin = rsin;
    return this;
  }

   /**
   * Get rsin
   * @return rsin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRsin() {
    return rsin;
  }


  public void setRsin(String rsin) {
    this.rsin = rsin;
  }


  public CorrespondentieAdresEigenaar identificatieHandelsregisterNatuurlijkPersoon(String identificatieHandelsregisterNatuurlijkPersoon) {
    
    this.identificatieHandelsregisterNatuurlijkPersoon = identificatieHandelsregisterNatuurlijkPersoon;
    return this;
  }

   /**
   * Get identificatieHandelsregisterNatuurlijkPersoon
   * @return identificatieHandelsregisterNatuurlijkPersoon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIdentificatieHandelsregisterNatuurlijkPersoon() {
    return identificatieHandelsregisterNatuurlijkPersoon;
  }


  public void setIdentificatieHandelsregisterNatuurlijkPersoon(String identificatieHandelsregisterNatuurlijkPersoon) {
    this.identificatieHandelsregisterNatuurlijkPersoon = identificatieHandelsregisterNatuurlijkPersoon;
  }


  public CorrespondentieAdresEigenaar aanschrijfwijze(String aanschrijfwijze) {
    
    this.aanschrijfwijze = aanschrijfwijze;
    return this;
  }

   /**
   * Samengestelde naam zoals die in communicatie met de eigenaar dient te worden. Hoe het samenstellen van een aanschrijfwijze te werk gaat is beschreven in de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-HR-Bevragen/blob/master/features/aanschrijfwijze.feature)
   * @return aanschrijfwijze
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Van de Graaf BV.", value = "Samengestelde naam zoals die in communicatie met de eigenaar dient te worden. Hoe het samenstellen van een aanschrijfwijze te werk gaat is beschreven in de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-HR-Bevragen/blob/master/features/aanschrijfwijze.feature)")

  public String getAanschrijfwijze() {
    return aanschrijfwijze;
  }


  public void setAanschrijfwijze(String aanschrijfwijze) {
    this.aanschrijfwijze = aanschrijfwijze;
  }


  public CorrespondentieAdresEigenaar adres(Adres adres) {
    
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Adres getAdres() {
    return adres;
  }


  public void setAdres(Adres adres) {
    this.adres = adres;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorrespondentieAdresEigenaar correspondentieAdresEigenaar = (CorrespondentieAdresEigenaar) o;
    return Objects.equals(this.rsin, correspondentieAdresEigenaar.rsin) &&
        Objects.equals(this.identificatieHandelsregisterNatuurlijkPersoon, correspondentieAdresEigenaar.identificatieHandelsregisterNatuurlijkPersoon) &&
        Objects.equals(this.aanschrijfwijze, correspondentieAdresEigenaar.aanschrijfwijze) &&
        Objects.equals(this.adres, correspondentieAdresEigenaar.adres);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rsin, identificatieHandelsregisterNatuurlijkPersoon, aanschrijfwijze, adres);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorrespondentieAdresEigenaar {\n");
    sb.append("    rsin: ").append(toIndentedString(rsin)).append("\n");
    sb.append("    identificatieHandelsregisterNatuurlijkPersoon: ").append(toIndentedString(identificatieHandelsregisterNatuurlijkPersoon)).append("\n");
    sb.append("    aanschrijfwijze: ").append(toIndentedString(aanschrijfwijze)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

