/*
 * Handelsregister bevragen
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op het Handelsregister beschikbaar gesteld.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.MaatschappelijkeActiviteitHalBasis;

/**
 * MaatschappelijkeActiviteitHalCollectieEmbedded
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-27T13:10:40.228Z[Etc/UTC]")
public class MaatschappelijkeActiviteitHalCollectieEmbedded {
  public static final String SERIALIZED_NAME_MAATSCHAPPELIJKE_ACTIVITEITEN = "maatschappelijkeActiviteiten";
  @SerializedName(SERIALIZED_NAME_MAATSCHAPPELIJKE_ACTIVITEITEN)
  private List<MaatschappelijkeActiviteitHalBasis> maatschappelijkeActiviteiten = null;


  public MaatschappelijkeActiviteitHalCollectieEmbedded maatschappelijkeActiviteiten(List<MaatschappelijkeActiviteitHalBasis> maatschappelijkeActiviteiten) {
    
    this.maatschappelijkeActiviteiten = maatschappelijkeActiviteiten;
    return this;
  }

  public MaatschappelijkeActiviteitHalCollectieEmbedded addMaatschappelijkeActiviteitenItem(MaatschappelijkeActiviteitHalBasis maatschappelijkeActiviteitenItem) {
    if (this.maatschappelijkeActiviteiten == null) {
      this.maatschappelijkeActiviteiten = new ArrayList<>();
    }
    this.maatschappelijkeActiviteiten.add(maatschappelijkeActiviteitenItem);
    return this;
  }

   /**
   * Get maatschappelijkeActiviteiten
   * @return maatschappelijkeActiviteiten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<MaatschappelijkeActiviteitHalBasis> getMaatschappelijkeActiviteiten() {
    return maatschappelijkeActiviteiten;
  }


  public void setMaatschappelijkeActiviteiten(List<MaatschappelijkeActiviteitHalBasis> maatschappelijkeActiviteiten) {
    this.maatschappelijkeActiviteiten = maatschappelijkeActiviteiten;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaatschappelijkeActiviteitHalCollectieEmbedded maatschappelijkeActiviteitHalCollectieEmbedded = (MaatschappelijkeActiviteitHalCollectieEmbedded) o;
    return Objects.equals(this.maatschappelijkeActiviteiten, maatschappelijkeActiviteitHalCollectieEmbedded.maatschappelijkeActiviteiten);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maatschappelijkeActiviteiten);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaatschappelijkeActiviteitHalCollectieEmbedded {\n");
    sb.append("    maatschappelijkeActiviteiten: ").append(toIndentedString(maatschappelijkeActiviteiten)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

