/*
 * Handelsregister bevragen
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op het Handelsregister beschikbaar gesteld.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MaatschappelijkeActiviteit
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-27T13:10:40.228Z[Etc/UTC]")
public class MaatschappelijkeActiviteit {
  public static final String SERIALIZED_NAME_KV_KNUMMER = "KvKnummer";
  @SerializedName(SERIALIZED_NAME_KV_KNUMMER)
  private String kvKnummer;

  public static final String SERIALIZED_NAME_NAAM = "naam";
  @SerializedName(SERIALIZED_NAME_NAAM)
  private String naam;

  public static final String SERIALIZED_NAME_NON_MAILING = "nonMailing";
  @SerializedName(SERIALIZED_NAME_NON_MAILING)
  private Boolean nonMailing;

  public static final String SERIALIZED_NAME_INCIDENTEEL_UITLENEN_ARBEIDSKRACHTEN = "incidenteelUitlenenArbeidskrachten";
  @SerializedName(SERIALIZED_NAME_INCIDENTEEL_UITLENEN_ARBEIDSKRACHTEN)
  private Boolean incidenteelUitlenenArbeidskrachten;

  public static final String SERIALIZED_NAME_NOTITIE = "notitie";
  @SerializedName(SERIALIZED_NAME_NOTITIE)
  private String notitie;

  public static final String SERIALIZED_NAME_ADRES_BERICHTENBOX = "adresBerichtenbox";
  @SerializedName(SERIALIZED_NAME_ADRES_BERICHTENBOX)
  private String adresBerichtenbox;


  public MaatschappelijkeActiviteit kvKnummer(String kvKnummer) {
    
    this.kvKnummer = kvKnummer;
    return this;
  }

   /**
   * Get kvKnummer
   * @return kvKnummer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getKvKnummer() {
    return kvKnummer;
  }


  public void setKvKnummer(String kvKnummer) {
    this.kvKnummer = kvKnummer;
  }


  public MaatschappelijkeActiviteit naam(String naam) {
    
    this.naam = naam;
    return this;
  }

   /**
   * Get naam
   * @return naam
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNaam() {
    return naam;
  }


  public void setNaam(String naam) {
    this.naam = naam;
  }


  public MaatschappelijkeActiviteit nonMailing(Boolean nonMailing) {
    
    this.nonMailing = nonMailing;
    return this;
  }

   /**
   * Get nonMailing
   * @return nonMailing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getNonMailing() {
    return nonMailing;
  }


  public void setNonMailing(Boolean nonMailing) {
    this.nonMailing = nonMailing;
  }


  public MaatschappelijkeActiviteit incidenteelUitlenenArbeidskrachten(Boolean incidenteelUitlenenArbeidskrachten) {
    
    this.incidenteelUitlenenArbeidskrachten = incidenteelUitlenenArbeidskrachten;
    return this;
  }

   /**
   * Get incidenteelUitlenenArbeidskrachten
   * @return incidenteelUitlenenArbeidskrachten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIncidenteelUitlenenArbeidskrachten() {
    return incidenteelUitlenenArbeidskrachten;
  }


  public void setIncidenteelUitlenenArbeidskrachten(Boolean incidenteelUitlenenArbeidskrachten) {
    this.incidenteelUitlenenArbeidskrachten = incidenteelUitlenenArbeidskrachten;
  }


  public MaatschappelijkeActiviteit notitie(String notitie) {
    
    this.notitie = notitie;
    return this;
  }

   /**
   * Get notitie
   * @return notitie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNotitie() {
    return notitie;
  }


  public void setNotitie(String notitie) {
    this.notitie = notitie;
  }


  public MaatschappelijkeActiviteit adresBerichtenbox(String adresBerichtenbox) {
    
    this.adresBerichtenbox = adresBerichtenbox;
    return this;
  }

   /**
   * Get adresBerichtenbox
   * @return adresBerichtenbox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAdresBerichtenbox() {
    return adresBerichtenbox;
  }


  public void setAdresBerichtenbox(String adresBerichtenbox) {
    this.adresBerichtenbox = adresBerichtenbox;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaatschappelijkeActiviteit maatschappelijkeActiviteit = (MaatschappelijkeActiviteit) o;
    return Objects.equals(this.kvKnummer, maatschappelijkeActiviteit.kvKnummer) &&
        Objects.equals(this.naam, maatschappelijkeActiviteit.naam) &&
        Objects.equals(this.nonMailing, maatschappelijkeActiviteit.nonMailing) &&
        Objects.equals(this.incidenteelUitlenenArbeidskrachten, maatschappelijkeActiviteit.incidenteelUitlenenArbeidskrachten) &&
        Objects.equals(this.notitie, maatschappelijkeActiviteit.notitie) &&
        Objects.equals(this.adresBerichtenbox, maatschappelijkeActiviteit.adresBerichtenbox);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kvKnummer, naam, nonMailing, incidenteelUitlenenArbeidskrachten, notitie, adresBerichtenbox);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaatschappelijkeActiviteit {\n");
    sb.append("    kvKnummer: ").append(toIndentedString(kvKnummer)).append("\n");
    sb.append("    naam: ").append(toIndentedString(naam)).append("\n");
    sb.append("    nonMailing: ").append(toIndentedString(nonMailing)).append("\n");
    sb.append("    incidenteelUitlenenArbeidskrachten: ").append(toIndentedString(incidenteelUitlenenArbeidskrachten)).append("\n");
    sb.append("    notitie: ").append(toIndentedString(notitie)).append("\n");
    sb.append("    adresBerichtenbox: ").append(toIndentedString(adresBerichtenbox)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

