/*
 * Handelsregister bevragen
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op het Handelsregister beschikbaar gesteld.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.VestigingsAdresEigenaarHalBasis;

/**
 * VestigingsAdresEigenaarHalCollectieEmbedded
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-27T13:10:40.228Z[Etc/UTC]")
public class VestigingsAdresEigenaarHalCollectieEmbedded {
  public static final String SERIALIZED_NAME_ADRESSEN = "adressen";
  @SerializedName(SERIALIZED_NAME_ADRESSEN)
  private List<VestigingsAdresEigenaarHalBasis> adressen = null;


  public VestigingsAdresEigenaarHalCollectieEmbedded adressen(List<VestigingsAdresEigenaarHalBasis> adressen) {
    
    this.adressen = adressen;
    return this;
  }

  public VestigingsAdresEigenaarHalCollectieEmbedded addAdressenItem(VestigingsAdresEigenaarHalBasis adressenItem) {
    if (this.adressen == null) {
      this.adressen = new ArrayList<>();
    }
    this.adressen.add(adressenItem);
    return this;
  }

   /**
   * Get adressen
   * @return adressen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<VestigingsAdresEigenaarHalBasis> getAdressen() {
    return adressen;
  }


  public void setAdressen(List<VestigingsAdresEigenaarHalBasis> adressen) {
    this.adressen = adressen;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VestigingsAdresEigenaarHalCollectieEmbedded vestigingsAdresEigenaarHalCollectieEmbedded = (VestigingsAdresEigenaarHalCollectieEmbedded) o;
    return Objects.equals(this.adressen, vestigingsAdresEigenaarHalCollectieEmbedded.adressen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adressen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VestigingsAdresEigenaarHalCollectieEmbedded {\n");
    sb.append("    adressen: ").append(toIndentedString(adressen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

