/*
 * Handelsregister bevragen
 * D.m.v. deze toepassing worden meerdere, korte bevragingen op het Handelsregister beschikbaar gesteld.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Adres;
import org.openapitools.client.model.VestigingsAdresEigenaar;
import org.openapitools.client.model.VestigingsAdresEigenaarHalBasisAllOf;
import org.openapitools.client.model.VestigingsAdresEigenaarLinks;

/**
 * VestigingsAdresEigenaarHalBasis
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-27T13:10:40.228Z[Etc/UTC]")
public class VestigingsAdresEigenaarHalBasis {
  public static final String SERIALIZED_NAME_RSIN = "rsin";
  @SerializedName(SERIALIZED_NAME_RSIN)
  private String rsin;

  public static final String SERIALIZED_NAME_IDENTIFICATIE_HANDELSREGISTER_NATUURLIJK_PERSOON = "identificatieHandelsregisterNatuurlijkPersoon";
  @SerializedName(SERIALIZED_NAME_IDENTIFICATIE_HANDELSREGISTER_NATUURLIJK_PERSOON)
  private String identificatieHandelsregisterNatuurlijkPersoon;

  public static final String SERIALIZED_NAME_ADRES = "adres";
  @SerializedName(SERIALIZED_NAME_ADRES)
  private Adres adres;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private VestigingsAdresEigenaarLinks links;


  public VestigingsAdresEigenaarHalBasis rsin(String rsin) {
    
    this.rsin = rsin;
    return this;
  }

   /**
   * Get rsin
   * @return rsin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRsin() {
    return rsin;
  }


  public void setRsin(String rsin) {
    this.rsin = rsin;
  }


  public VestigingsAdresEigenaarHalBasis identificatieHandelsregisterNatuurlijkPersoon(String identificatieHandelsregisterNatuurlijkPersoon) {
    
    this.identificatieHandelsregisterNatuurlijkPersoon = identificatieHandelsregisterNatuurlijkPersoon;
    return this;
  }

   /**
   * Get identificatieHandelsregisterNatuurlijkPersoon
   * @return identificatieHandelsregisterNatuurlijkPersoon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIdentificatieHandelsregisterNatuurlijkPersoon() {
    return identificatieHandelsregisterNatuurlijkPersoon;
  }


  public void setIdentificatieHandelsregisterNatuurlijkPersoon(String identificatieHandelsregisterNatuurlijkPersoon) {
    this.identificatieHandelsregisterNatuurlijkPersoon = identificatieHandelsregisterNatuurlijkPersoon;
  }


  public VestigingsAdresEigenaarHalBasis adres(Adres adres) {
    
    this.adres = adres;
    return this;
  }

   /**
   * Get adres
   * @return adres
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Adres getAdres() {
    return adres;
  }


  public void setAdres(Adres adres) {
    this.adres = adres;
  }


  public VestigingsAdresEigenaarHalBasis links(VestigingsAdresEigenaarLinks links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VestigingsAdresEigenaarLinks getLinks() {
    return links;
  }


  public void setLinks(VestigingsAdresEigenaarLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VestigingsAdresEigenaarHalBasis vestigingsAdresEigenaarHalBasis = (VestigingsAdresEigenaarHalBasis) o;
    return Objects.equals(this.rsin, vestigingsAdresEigenaarHalBasis.rsin) &&
        Objects.equals(this.identificatieHandelsregisterNatuurlijkPersoon, vestigingsAdresEigenaarHalBasis.identificatieHandelsregisterNatuurlijkPersoon) &&
        Objects.equals(this.adres, vestigingsAdresEigenaarHalBasis.adres) &&
        Objects.equals(this.links, vestigingsAdresEigenaarHalBasis.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rsin, identificatieHandelsregisterNatuurlijkPersoon, adres, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VestigingsAdresEigenaarHalBasis {\n");
    sb.append("    rsin: ").append(toIndentedString(rsin)).append("\n");
    sb.append("    identificatieHandelsregisterNatuurlijkPersoon: ").append(toIndentedString(identificatieHandelsregisterNatuurlijkPersoon)).append("\n");
    sb.append("    adres: ").append(toIndentedString(adres)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

